server:
  port: 80

spring:
  application:
    name: cloud-order-service



eureka:
  instance:
    instance-id: order80
    prefer-ip-address: true
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    serviceUrl:
      #集群版配置
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #单机版配置
      #defaultZone: http://localhost:7001/eureka/
    #是否从EureekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true